LOCATIONS = {
    "Abia": {
        "lgas": [
            "Aba North",
            "Aba South",
            "Arochukwu",
            "Bende",
            "Ikwuano",
            "Isiala Ngwa North",
            "Isiala Ngwa South",
            "Isuikwuato",
            "Obi Ngwa",
            "Ohafia",
            "Osisioma",
            "Ugwunagbo",
            "Ukwa East",
            "Ukwa West",
            "Umuahia North",
            "Umuahia South",
            "Nneochi",
        ],
        "cities": ["Aba", "Umuahia", "Arochukwu", "Ohafia", "Umunneochi"],
        "institutions": [
            "Abia State University, Uturu (ABSU)",
            "Michael Okpara University of Agriculture, Umudike (MOUAU)",
            "Rhema University, Aba",
            "Gregory University, Uturu",
            "Clifford University, Owerrinta",
            "Ogbonnaya Onu Polytechnic (formerly Abia State Polytechnic)",
            "Covenant Polytechnic",
            "Temple Gate Polytechnic",
            "Abia State College of Education(Technical), Arochukwu",
            "Havard Wilson College of Education, Aba",
            "Diamond College of Education, Aba",
            "Covenant College of Education (CCOE)",
            "Federal College of Education, Ofeme",
        ],
    },
    "Adamawa": {
        "lgas": [
            "Demsa",
            "Fufore",
            "Ganye",
            "Gayuk",
            "Girei",
            "Hong",
            "Jada",
            "Lamurde",
            "Madagali",
            "Maiha",
            "Mayo Belwa",
            "Michika",
            "Mubi North",
            "Mubi South",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola North",
            "Yola South",
        ],
        "cities": ["Yola", "Mubi", "Numan", "Jalingo"],
        "institutions": [
            "Modibbo Adama University of Technology, Yola (MAUTECH)",
            "Adamawa State University, Mubi",
            "American University of Nigeria, Yola",
            "Federal Polytechnic, Mubi",
            "Adamawa State Polytechnic, Yola",
            "Federal College of Education, Yola",
            "Adamawa State College of Education, Hong",
        ],
    },
    "Akwa Ibom": {
        "lgas": [
            "Abak",
            "Eastern Obolo",
            "Eket",
            "Esit Eket",
            "Essien Udim",
            "Etim Ekpo",
            "Etinan",
            "Ibeno",
            "Ibesikpo Asutan",
            "Ibiono Ibom",
            "Ika",
            "Ikono",
            "Ikot Abasi",
            "Ikot Ekpene",
            "Ini",
            "Itu",
            "Mbo",
            "Mkpat Enin",
            "Nsit Atai",
            "Nsit Ibom",
            "Nsit Ubium",
            "Obot Akara",
            "Onna",
            "Oron",
            "Oruk Anam",
            "Udung Uko",
            "Uruan",
            "Urue-Offong/Oruko",
            "Uyo",
        ],
        "cities": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Ikot Abasi"],
        "institutions": [
            "University of Uyo (UNIUYO)",
            "Akwa Ibom State University (AKSU)",
            "Obong University, Obong Nsit",
            "Topfaith University, Mkpatak",
            "Ritman University, Ikot Ekpene",
            "Federal University of Technology, Ikot Abasi",
            "Obong University",
            "Wellspring University, Evbuobanosa",
            "Akwa Ibom State College of Science and Technology, Ikot Ekpene",
            "National Open University of Nigeria (NOUN)",
            "Akwa Ibom State Polytechnic, Ikot Osurua",
            "Ibom Metropolitan Polytechnic, Uyo",
            "Trinity Polytechnic, Uyo",
            "Sure Foundation Polytechnic, Ukanafun",
            "Akwa Ibom State College of Education, Afaha Nsit",
        ],
    },
    "Anambra": {
        "lgas": [
            "Anambra East",
            "Anambra West",
            "Anaocha",
            "Awka North",
            "Awka South",
            "Ayamelum",
            "Dunukofia",
            "Ekwusigo",
            "Idemili North",
            "Idemili South",
            "Ihiala",
            "Njikoka",
            "Nnewi North",
            "Nnewi South",
            "Ogbaru",
            "Onitsha North",
            "Onitsha South",
            "Orumba North",
            "Orumba South",
            "Oyi",
        ],
        "cities": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
        "institutions": [
            "Nnamdi Azikiwe University, Awka (UNIZIK)",
            "Chukwuemeka Odumegwu Ojukwu University, Uli (Formerly Anambra State University)",
            "Paul University, Awka",
            "Tansian University, Umunya",
            "Legacy University, Okija",
            "Madonna University, Okija",
            "Peter University, Achina-Onneh",
            "Federal Polytechnic, Oko",
            "Anambra State Polytechnic, Mgbaukwu",
            "Nwafor Orizu College of Education, Nsugbe",
            "Federal College of Education (Technical), Umunze",
            "The UA College of Science and Technology",
            "Ekwenugo Okeke Polytechnic, Uli",
        ],
    },
    "Bauchi": {
        "lgas": [
            "Alkaleri",
            "Bauchi",
            "Bogoro",
            "Damban",
            "Darazo",
            "Dass",
            "Gamawa",
            "Ganjuwa",
            "Giade",
            "Itas/Gadau",
            "Jama'are",
            "Katagum",
            "Kirfi",
            "Misau",
            "Ningi",
            "Shira",
            "Tafawa Balewa",
            "Toro",
            "Warji",
            "Zaki",
        ],
        "cities": ["Bauchi", "Azare", "Misau", "Tafawa Balewa"],
        "institutions": [
            "Abubakar Tafawa Balewa University, Bauchi (ATBU)",
            "Sa'adu Zungur UniversityBauchi State University), Gadau",
            "Federal Polytechnic Bauchi",
            "Abubakar Tatari Ali Polytechnic",
            "Federal College of Education, Jama'are",
            "Bilyaminu Othman College of Education, Dass",
            "Sunnah College of Education",
            "Bogoro College of Education,Bogoro",
            "Climax College of Education, Bauchi",
        ],
    },
    "Bayelsa": {
        "lgas": [
            "Brass",
            "Ekeremor",
            "Kolokuma/Opokuma",
            "Nembe",
            "Ogbia",
            "Sagbama",
            "Southern Ijaw",
            "Yenagoa",
        ],
        "cities": ["Yenagoa", "Amassoma", "Nembe", "Brass"],
        "institutions": [
            "Niger Delta University, Yenagoa (NDU)",
            "Federal University, Otuoke",
            "Bayelsa Medical University, Yenagoa",
            "University of Africa, Toru-Orua (UAT)",
            "Federal Polytechnic, Ekowe",
            "Bayelsa State College of Arts and Science, Ogbia",
            "Nembe State College of Education, Nembe",
            "Federal Polytechnic, Ekowe",
            "Isaac Jasper Boro College of Education, Sagbama",
        ],
    },
    "Benue": {
        "lgas": [
            "Ado",
            "Agatu",
            "Apa",
            "Awe",
            "Buruku",
            "Gboko",
            "Gwer East",
            "Gwer West",
            "Katsina-Ala",
            "Konshisha",
            "Kwande",
            "Logo",
            "Makurdi",
            "Obi",
            "Ogbadibo",
            "Ohimini",
            "Oju",
            "Okpokwu",
            "Oturkpo",
            "Tarka",
            "Ukum",
            "Ushongo",
            "Vandeikya",
        ],
        "cities": ["Makurdi", "Gboko", "Oturkpo", "Katsina-Ala"],
        "institutions": [
            "Joseph Sarwuan Tarka University, Makurdi (formerly Federal University of Agriculture, Makurdi)",
            "Benue State University, Makurdi (BSU)",
            "Benue State Polytechnic, Ugbokolo",
            "Fidei Polytechnic, Gboko",
            "Federal College of Education, Odugbo",
            "Federal College of Education, Agasha",
            "College of Education, Oju",
            "College of Education, Katsina-Ala",
            "University of Mkar, Mkar",
        ],
    },
    "Borno": {
        "lgas": [
            "Abadam",
            "Askira/Uba",
            "Bama",
            "Bayo",
            "Biu",
            "Chibok",
            "Damboa",
            "Dikwa",
            "Gubio",
            "Guzamala",
            "Gwoza",
            "Hawul",
            "Jere",
            "Kaga",
            "Kala/Balge",
            "Konduga",
            "Kukawa",
            "Kwaya Kusar",
            "Maiduguri",
            "Magumeri",
            "Marte",
            "Mobbar",
            "Monguno",
            "Ngala",
            "Nganzai",
            "Shani",
        ],
        "cities": ["Maiduguri", "Biu", "Dikwa", "Monguno"],
        "institutions": [
            "University of Maiduguri (UNIMAID)",
            "Kashim Ibrahim University (formerly Borno State University), Maiduguri",
            "Federal Polytechnic, Monguno",
            "Ramat Polytechnic, Maiduguri",
            "Abubakar Tatari Ali Polytechnic",
            "A.D. Rufa'i College for Islamic and Legal Studies",
            "Maimadu College of Education, Maiduguri",
            "Federal College of Education, Gwoza",
        ],
    },
    "Cross River": {
        "lgas": [
            "Abi",
            "Akamkpa",
            "Akpabuyo",
            "Bakassi",
            "Bekwarra",
            "Biase",
            "Boki",
            "Calabar Municipal",
            "Calabar South",
            "Etung",
            "Ikom",
            "Obanliku",
            "Obubra",
            "Obudu",
            "Odukpani",
            "Ogoja",
            "Yakuur",
            "Yala",
        ],
        "cities": ["Calabar", "Ogoja", "Ikom", "Obudu", "Obanliku"],
        "institutions": [
            "University of Calabar (UNICAL)",
            "Cross River University of Technology, Calabar (CRUTECH)",
            "Havilla University, Nde-Ikom",
            "Federal Polytechnic, Ugep",
            "State Collge of Education",
        ],
    },
    "Delta": {
        "lgas": [
            "Aniocha North",
            "Aniocha South",
            "Bomadi",
            "Burutu",
            "Ethiope East",
            "Ethiope West",
            "Ika North East",
            "Ika South",
            "Isoko North",
            "Isoko South",
            "Ndokwa East",
            "Ndokwa West",
            "Okpe",
            "Oshimili North",
            "Oshimili South",
            "Patani",
            "Sapele",
            "Udu",
            "Ughelli North",
            "Ughelli South",
            "Ukwuani",
            "Uvwie",
            "Warri North",
            "Warri South",
            "Warri South West",
        ],
        "cities": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
        "institutions": [
            "Delta State University, Abraka (DELSU)",
            "Federal University of Petroleum Resources, Effurun (FUPRE)",
            "Novena University, Ogume",
            "Western Delta University, Oghara",
            "University of Delta, Agbor",
            "Delta State Polytechnic",
            "Delta State University (DELSU), Abraka",
            "Federal College of Education (Technical), Asaba",
            "College of Education, Warri",
            "Delta State School of Marine Technology, Burutu",
            "Michael and Cecilia Ibru University, Agbarha-Otor",
            "Novena University, Ogume-Amai",
            "Edwin Clark University, Kiagbodo",
            "Admiralty University of Nigeria, Ibusa",
            "Dennis Osadebay University, Asaba",
        ],
    },
    "Ebonyi": {
        "lgas": [
            "Afikpo North",
            "Afikpo South",
            "Ezza North",
            "Ezza South",
            "Ikwo",
            "Ishielu",
            "Ivo",
            "Izzi",
            "Ohaozara",
            "Ohaukwu",
            "Onicha",
        ],
        "cities": ["Abakaliki", "Afikpo"],
        "institutions": [
            "Ebonyi State University, Abakaliki (EBSU)",
            "Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)",
            "Evangel University, Okpoto",
            "Akanu Ibiam Federal Polytechnic, Unwana",
            "Federal College of Education(Technical)Federal College of Agriculture",
        ],
    },
    "Edo": {
        "lgas": [
            "Akoko Edo",
            "Egor",
            "Esan Central",
            "Esan North-East",
            "Esan South-East",
            "Esan West",
            "Etsako Central",
            "Etsako East",
            "Etsako West",
            "Igueben",
            "Ikpoba Okha",
            "Orhionmwon",
            "Oredo",
            "Ovia North-East",
            "Ovia South-West",
            "Owan East",
            "Owan West",
            "Uhunmwonde",
        ],
        "cities": ["Benin City", "Auchi", "Ekpoma", "Uromi"],
        "institutions": [
            "University of Benin (UNIBEN)",
            "Ambrose Alli University, Ekpoma (AAU)",
            "Igbinedion University, Okada",
            "Benson Idahosa University",
            "Glorious Vision University (formerly Samuel Adegboyega University), Ogwa",
            "Wellspring University",
            "Igbinedion University, Okada",
            "Mudiame University",
            "Edo State Polytechnic",
            "Agenebode College of Education, Agenebode",
            "College of Education, Ekiadolor",
            "Edo Technical College, Benin City",
            "Benin Technical College, Benin City",
        ],
    },
    "Ekiti": {
        "lgas": [
            "Ado Ekiti",
            "Efon",
            "Ekiti East",
            "Ekiti South-West",
            "Ekiti West",
            "Emure",
            "Gbonyin",
            "Ido Osi",
            "Ijero",
            "Ikere",
            "Ilejemeje",
            "Irepodun/Ifelodun",
            "Ise/Orun",
            "Moba",
            "Oye",
        ],
        "cities": [
            "Ado-Ekiti",
            "Ikere-Ekiti",
            "Oye-Ekiti",
            "Ise-Ekiti",
            "Efon-Alaaye",
        ],
        "institutions": [
            "Ekiti State University, Ado-Ekiti (EKSU)",
            "Federal University, Oye-Ekiti (FUOYE)",
            "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
            "Afe Babalola University, Ado-Ekiti (ABUAD)",
            "Federal Polytechnic, Ado-Ekiti",
            "Ekiti State Polytechnic, Isan Ekiti",
            "Ekiti State University (EKSU)",
        ],
    },
    "Enugu": {
        "lgas": [
            "Aninri",
            "Awgu",
            "Enugu East",
            "Enugu North",
            "Enugu South",
            "Ezeagu",
            "Igbo Etiti",
            "Igbo Eze North",
            "Igbo Eze South",
            "Isi Uzo",
            "Nkanu East",
            "Nkanu West",
            "Nsukka",
            "Oji River",
            "Udenu",
            "Udi",
            "Uzo Uwani",
        ],
        "cities": ["Enugu", "Nsukka", "Awgu", "Oji River", "Udi"],
        "institutions": [
            "University of Nigeria, Nsukka (UNN)",
            "Enugu State University of Science and Technology (ESUT)",
            "Coal City University, Enugu",
            "Godfrey Okoye University, Ugwuomu-Nike",
            "Caritas University, Amorji-Nike",
            "Enugu State Polytechnic, Iwollo",
            "Maduka University",
            "Institute of Management and Technology (IMT), Enugu",
            "Enugu State College of Education (Technical), Enugu",
            "Federal College of Education, Eha-Amufu",
            "Renaissance University, Ugbawka",
            "The College of Education, Nsukka",
            "Evangel University, Akaeze",
            "Federal School of Dental Technology & Therapy",
            "Osisatech Polytechnic",
            "Marist Polytechnic",
            "Peacland University",
            "Peaceland College of Education",
            "Institute of Ecumenical Education",
        ],
    },
    "Gombe": {
        "lgas": [
            "Akko",
            "Balanga",
            "Billiri",
            "Dukku",
            "Funakaye",
            "Gombe",
            "Kaltungo",
            "Kwami",
            "Nafada",
            "Shongom",
            "Yamaltu/Deba",
        ],
        "cities": ["Gombe", "Dukku", "Kaltungo", "Bajoga"],
        "institutions": [
            "Gombe State University (GSU)",
            "Federal University, Kashere",
        ],
    },
    "Imo": {
        "lgas": [
            "Aboh Mbaise",
            "Ahiazu Mbaise",
            "Ehime Mbano",
            "Ezinihitte",
            "Ideato North",
            "Ideato South",
            "Ihitte/Uboma",
            "Ikeduru",
            "Isiala Mbano",
            "Isu",
            "Mbaitoli",
            "Ngor Okpala",
            "Njaba",
            "Nkwerre",
            "Nwangele",
            "Obowo",
            "Oguta",
            "Ohaji/Egbema",
            "Okigwe",
            "Orlu",
            "Orsu",
            "Oru East",
            "Oru West",
            "Owerri Municipal",
            "Owerri North",
            "Owerri West",
            "Unuimo",
        ],
        "cities": ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
        "institutions": [
            "Imo State University, Owerri (IMSU)",
            "Federal University of Technology, Owerri (FUTO)",
            "Hezekiah University, Umudi",
            "Eastern Palm University, Ogboko",
            "Gregory University, Uturu",
        ],
    },
    "Jigawa": {
        "lgas": [
            "Auyo",
            "Babura",
            "Biriniwa",
            "Birnin Kudu",
            "Buji",
            "Dutse",
            "Gagarawa",
            "Garki",
            "Gumel",
            "Guri",
            "Gwaram",
            "Gwiwa",
            "Hadejia",
            "Jahun",
            "Kafin Hausa",
            "Kazaure",
            "Kiri Kasama",
            "Kiyawa",
            "Kaugama",
            "Maigatari",
            "Malam Madori",
            "Miga",
            "Ringim",
            "Roni",
            "Sule Tankarkar",
            "Taura",
            "Yankwashi",
        ],
        "cities": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Birnin Kudu"],
        "institutions": [
            "Federal University, Dutse (FUD)",
            "Jigawa State University, Kafin Hausa",
            "Hussaini Adamu Federal Polytechnic, Kazaure",
        ],
    },
    "Kaduna": {
        "lgas": [
            "Birnin Gwari",
            "Chikun",
            "Giwa",
            "Igabi",
            "Ikara",
            "Jaba",
            "Jema'a",
            "Kachia",
            "Kaduna North",
            "Kaduna South",
            "Kagarko",
            "Kajuru",
            "Kaura",
            "Kauru",
            "Kubau",
            "Kudan",
            "Lere",
            "Makarfi",
            "Sabon Gari",
            "Sanga",
            "Soba",
            "Zangon Kataf",
            "Zaria",
        ],
        "cities": ["Kaduna", "Zaria", "Kafanchan", "Birnin Gwari", "Ikara"],
        "institutions": [
            "Ahmadu Bello University, Zaria (ABU)",
            "Kaduna State University (KASU)",
            "Nigerian Defence Academy, Kaduna",
            "Landmark University, Omu-Aran",
            "Greenfield University, Kaduna",
        ],
    },
    "Kano": {
        "lgas": [
            "Albasu",
            "Bagwai",
            "Bichi",
            "Bunkure",
            "Dala",
            "Dambatta",
            "Dawakin Kudu",
            "Dawakin Tofa",
            "Doguwa",
            "Fagge",
            "Gabasawa",
            "Garko",
            "Garun Mallam",
            "Gaya",
            "Gezawa",
            "Gwale",
            "Gwarzo",
            "Kabo",
            "Kano Municipal",
            "Karaye",
            "Kibiya",
            "Kiru",
            "Kumbotso",
            "Kunchi",
            "Kura",
            "Madobi",
            "Makoda",
            "Mandugu",
            "Matazu",
            "Minjibir",
            "Nasarawa",
            "Nipatse",
            "Rano",
            "Rimin Gado",
            "Rogo",
            "Shanono",
            "Sumaila",
            "Takai",
            "Tarabi",
            "Tarauni",
            "Tofa",
            "Tsanyawa",
            "Tudun Wada",
            "Ungogo",
            "Warawa",
            "Wudil",
        ],
        "cities": ["Kano", "Dala", "Rano", "Kumbotso", "Gwarzo"],
        "institutions": [
            "Bayero University, Kano (BUK)",
            "Kano University of Science and Technology, Wudil (KUST)",
            "Northwest University, Kano",
            "Al-Qalam University, Katsina",
            "Skyline University, Kano",
        ],
    },
    "Katsina": {
        "lgas": [
            "Bakori",
            "Batagarawa",
            "Batsari",
            "Baure",
            "Bindawa",
            "Charanchi",
            "Dandume",
            "Danja",
            "Dan Musa",
            "Daura",
            "Dutsi",
            "Dutsin Ma",
            "Faskari",
            "Funtua",
            "Ingawa",
            "Jibia",
            "Kafur",
            "Kaita",
            "Kajola",
            "Kalambo",
            "Kankara",
            "Kankia",
            "Katsina",
            "Kurfi",
            "Kusada",
            "Mai'Adua",
            "Malumfashi",
            "Mani",
            "Mashi",
            "Matazu",
            "Musawa",
            "Rimi",
            "Sabuwa",
            "Safana",
            "Sandamu",
            "Zango",
        ],
        "cities": ["Katsina", "Daura", "Funtua", "Malumfashi", "Kankia"],
        "institutions": [
            "Umaru Musa Yar'adua University, Katsina (UMYU)",
            "Federal University, Dutsin-Ma (FUDMA)",
            "Al-Qalam University, Katsina",
        ],
    },
    "Kebbi": {
        "lgas": [
            "Aleiro",
            "Argungu",
            "Arewa Dandi",
            "Augie",
            "Bagudo",
            "Birnin Kebbi",
            "Bunza",
            "Dandi",
            "Fakai",
            "Gwandu",
            "Jega",
            "Kalgo",
            "Koko/Besse",
            "Maiyama",
            "Ngaski",
            "Sakaba",
            "Shanga",
            "Suru",
            "Wasagu Danko",
            "Yauri",
            "Zuru",
        ],
        "cities": ["Birnin Kebbi", "Argungu", "Yauri", "Jega", "Zuru"],
        "institutions": [
            "Federal University, Birnin Kebbi (FUBK)",
            "Kebbi State University of Science and Technology, Aliero (KSUSTA)",
        ],
    },
    "Kogi": {
        "lgas": [
            "Ajaokuta",
            "Ankpa",
            "Bassa",
            "Dekina",
            "Ibaji",
            "Idah",
            "Igalamela Odolu",
            "Ijumu",
            "Kabba/Bunu",
            "Kogi",
            "Lokoja",
            "Ofu",
            "Ogori/Magongo",
            "Okehi",
            "Okene",
            "Olamaboro",
            "Omala",
            "Yagba East",
            "Yagba West",
        ],
        "cities": ["Lokoja", "Okene", "Kabba", "Ankpa", "Idah"],
        "institutions": [
            "Federal University, Lokoja (FULokoja)",
            "Kogi State University, Anyigba (KSU)",
            "Prince Abubakar Audu University, Anyigba",
            "Confluence University of Science and Technology, Osara",
        ],
    },
    "Kwara": {
        "lgas": [
            "Asa",
            "Baruten",
            "Edu",
            "Ekiti",
            "Ifelodun",
            "Ilorin East",
            "Ilorin South",
            "Ilorin West",
            "Irepodun",
            "Isin",
            "Kaiama",
            "Moro",
            "Offa",
            "Oke Ero",
            "Oyun",
            "Pategi",
        ],
        "cities": ["Ilorin", "Offa", "Omu-Aran", "Patigi", "Lafiagi"],
        "institutions": [
            "University of Ilorin (UNILORIN)",
            "Kwara State University, Malete (KWASU)",
            "Al-Hikmah University, Ilorin",
            "Landmark University, Omu-Aran",
            "Crown Hill University, Eiyenkorin",
        ],
    },
    "Lagos": {
        "lgas": [
            "Agege",
            "Ajeromi-Ifelodun",
            "Alimosho",
            "Amuwo-Odofin",
            "Badagry",
            "Epe",
            "Eti-Osa",
            "Ibeju-Lekki",
            "Ifako-Ijaiye",
            "Ikeja",
            "Ikorodu",
            "Kosofe",
            "Lagos Island",
            "Lagos Mainland",
            "Mushin",
            "Ojo",
            "Oshodi-Isolo",
            "Shomolu",
            "Surulere",
        ],
        "cities": ["Lagos", "Ikeja", "Badagry", "Epe", "Ikorodu"],
        "institutions": [
            "University of Lagos (UNILAG)",
            "Lagos State University, Ojo (LASU)",
            "Pan-Atlantic University, Lagos",
            "Caleb University, Imota",
            "Augustine University, Ilara",
            "Anchor University, Ayobo",
            "Miva Open University, Lagos",
            "Lagos State University of Science and Technology",
        ],
    },
    "Nasarawa": {
        "lgas": [
            "Akwanga",
            "Awe",
            "Doma",
            "Karu",
            "Keana",
            "Keffi",
            "Kokona",
            "Lafia",
            "Nasarawa",
            "Nasarawa Egon",
            "Obi",
            "Toto",
            "Wamba",
        ],
        "cities": ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Keana"],
        "institutions": [
            "Federal University, Lafia (FULafia)",
            "Nasarawa State University, Keffi (NSUK)",
            "Veritas University, Abuja",
        ],
    },
    "Niger": {
        "lgas": [
            "Agaie",
            "Agwara",
            "Bida",
            "Borgu",
            "Bosso",
            "Chanchaga",
            "Edati",
            "Gurara",
            "Katcha",
            "Kontagora",
            "Lapai",
            "Lavun",
            "Magama",
            "Mariga",
            "Mashegu",
            "Mokwa",
            "Moya",
            "Paikoro",
            "Rafi",
            "Rijau",
            "Shiroro",
            "Suleja",
            "Tafa",
            "Wushishi",
        ],
        "cities": ["Minna", "Bida", "Suleja", "Kontagora", "Lapai"],
        "institutions": [
            "Federal University of Technology, Minna (FUTMinna)",
            "Ibrahim Badamasi Babangida University, Lapai (IBBU)",
            "Niger State University of Education",
        ],
    },
    "Ogun": {
        "lgas": [
            "Abeokuta North",
            "Abeokuta South",
            "Ado-Odo/Ota",
            "Egbado North",
            "Egbado South",
            "Ifo",
            "Ijebu East",
            "Ijebu North",
            "Ijebu North East",
            "Ijebu Ode",
            "Ikenne",
            "Imeko Afon",
            "Ipokia",
            "Obafemi Owode",
            "Odeda",
            "Odogbolu",
            "Ogun Waterside",
            "Remo North",
            "Shagamu",
        ],
        "cities": ["Abeokuta", "Ijebu Ode", "Sagamu", "Ikenne", "Ota"],
        "institutions": [
            "Federal University of Agriculture, Abeokuta (FUNAAB)",
            "Olabisi Onabanjo University, Ago Iwoye (OOU)",
            "Babcock University, Ilishan-Remo",
            "Covenant University, Ota",
            "Bells University of Technology, Ota",
            "Chrisland University, Owode",
            "Mountain Top University, Makogi-Oba",
        ],
    },
    "Ondo": {
        "lgas": [
            "Akoko North East",
            "Akoko North West",
            "Akoko South East",
            "Akoko South West",
            "Akure North",
            "Akure South",
            "Ese Odo",
            "Idanre",
            "Ifedore",
            "Ilaje",
            "Ile Oluji/Okeigbo",
            "Irele",
            "Lafrancis",
            "Odigbo",
            "Okitipupa",
            "Ondo",
            "Ose",
            "Owo",
        ],
        "cities": ["Akure", "Ondo", "Owo", "Ikare-Akoko", "Okitipupa"],
        "institutions": [
            "Federal University of Technology, Akure (FUTA)",
            "Adekunle Ajasin University, Akungba-Akoko (AAUA)",
            "Ondo State University of Science and Technology, Okitipupa",
            "Achievers University, Owo",
            "Elizade University, Ilara-Mokin",
        ],
    },
    "Osun": {
        "lgas": [
            "Aiyedaade",
            "Aiyedire",
            "Atakumosa East",
            "Atakumosa West",
            "Boluwaduro",
            "Boripe",
            "Ede North",
            "Ede South",
            "Egbedore",
            "Ejigbo",
            "Ifedayo",
            "Ifelodun",
            "Ife Central",
            "Ife East",
            "Ife North",
            "Ife South",
            "Egbedore",
            "Ilesa East",
            "Ilesa West",
            "Irepodun",
            "Irewole",
            "Isokan",
            "Iwo",
            "Obokun",
            "Odo Otin",
            "Ola Oluwa",
            "Olorunda",
            "Oriade",
            "Orolu",
            "Osogbo",
        ],
        "cities": ["Osogbo", "Ile-Ife", "Ilesa", "Iwo", "Ede"],
        "institutions": [
            "Obafemi Awolowo University, Ile-Ife (OAU)",
            "Osun State University, Osogbo (UNIOSUN)",
            "Adeleke University, Ede",
            "Oduduwa University, Ipetumodu",
            "Kings University, Ode Omu",
            "Bowen University, Iwo",
        ],
    },
    "Oyo": {
        "lgas": [
            "Afijio",
            "Akinyele",
            "Atiba",
            "Atisbo",
            "Egbeda",
            "Ibadan North",
            "Ibadan North-East",
            "Ibadan North-West",
            "Ibadan South-East",
            "Ibadan South-West",
            "Ibarapa Central",
            "Ibarapa East",
            "Ibarapa North",
            "Ido",
            "Irepo",
            "Iseyin",
            "Itesiwaju",
            "Iwajowa",
            "Kajola",
            "Lagelu",
            "Ogbomosho North",
            "Ogbomosho South",
            "Ogo Oluwa",
            "Olorunsogo",
            "Oluyole",
            "Ona Ara",
            "Orelope",
            "Ori Ire",
            "Oyo",
            "Oyo East",
            "Saki East",
            "Saki West",
            "Surulere (Oyo)",
        ],
        "cities": ["Ibadan", "Oyo", "Ogbomosho", "Saki", "Iseyin"],
        "institutions": [
            "University of Ibadan (UI)",
            "Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)",
            "The Polytechnic, Ibadan",
            "Precious Cornerstone University, Ibadan",
            "Ajayi Crowther University, Oyo",
            "Kola Daisi University, Ibadan",
            "Dominion University, Ibadan",
        ],
    },
    "Plateau": {
        "lgas": [
            "Barkin Ladi",
            "Bassa",
            "Bokkos",
            "Jos East",
            "Jos North",
            "Jos South",
            "Kanam",
            "Kanke",
            "Langtang South",
            "Langtang North",
            "Mangu",
            "Mikang",
            "Pankshin",
            "Qua'an Pan",
            "Riyom",
            "Shendam",
            "Wase",
        ],
        "cities": ["Jos", "Bukuru", "Mangu", "Pankshin", "Shendam"],
        "institutions": [
            "University of Jos (UNIJOS)",
            "Plateau State University, Bokkos",
            "University of Africa, Toru Orua",
        ],
    },
    "Rivers": {
        "lgas": [
            "Abua/Odual",
            "Ahoada East",
            "Ahoada West",
            "Akuku Toru",
            "Andoni",
            "Asari Toru",
            "Bonny",
            "Degema",
            "Eleme",
            "Emuoha",
            "Etche",
            "Gokana",
            "Ikwerre",
            "Khana",
            "Obio/Akpor",
            "Ogba/Egbema/Ndoni",
            "Ogu/Bolo",
            "Okirika",
            "Omuma",
            "Opobo/Nkoro",
            "Oyigbo",
            "Port Harcourt",
            "Tai",
        ],
        "cities": ["Port Harcourt", "Bonny", "Okrika", "Bori", "Degema"],
        "institutions": [
            "University of Port Harcourt (UNIPORT)",
            "Rivers State University, Port Harcourt (RSU)",
            "Ignatius Ajuru University of Education, Port Harcourt",
            "PAMO University of Medical Sciences, Port Harcourt",
            "Kenule Beeson Saro-Wiwa Polytechnic, Bori",
        ],
    },
    "Sokoto": {
        "lgas": [
            "Binji",
            "Bodinga",
            "Dange Shuni",
            "Gada",
            "Goronyo",
            "Gudu",
            "Gwadabawa",
            "Illela",
            "Isa",
            "Kebbe",
            "Kware",
            "Rabah",
            "Sabon Birni",
            "Shagari",
            "Silame",
            "Sokoto North",
            "Sokoto South",
            "Tambuwal",
            "Tangaza",
            "Tureta",
            "Wamako",
            "Wurno",
        ],
        "cities": ["Sokoto", "Tambuwal", "Binji", "Illela"],
        "institutions": [
            "Usmanu Danfodiyo University, Sokoto (UDUSOK)",
            "Sokoto State University",
            "Umaru Ali Shinkafi Polytechnic, Sokoto",
        ],
    },
    "Taraba": {
        "lgas": [
            "Ardo Kola",
            "Bali",
            "Donga",
            "Gashaka",
            "Gassol",
            "Ibi",
            "Jalingo",
            "Karim Lamido",
            "Katcha",
            "Kurmi",
            "Lau",
            "Sardauna",
            "Takum",
            "Ussa",
            "Wukari",
            "Yorro",
            "Zing",
        ],
        "cities": ["Jalingo", "Wukari", "Takum", "Gembu", "Katsina-Ala"],
        "institutions": [
            "Federal University, Wukari",
            "Taraba State University, Jalingo",
        ],
    },
    "Yobe": {
        "lgas": [
            "Bade",
            "Bursari",
            "Damaturu",
            "Fika",
            "Fune",
            "Geidam",
            "Gujba",
            "Gulani",
            "Jakusko",
            "Karasuwa",
            "Machina",
            "Nangere",
            "Nguru",
            "Potiskum",
            "Tarmuwa",
            "Yunusari",
            "Yusufari",
        ],
        "cities": ["Damaturu", "Potiskum", "Nguru", "Geidam", "Buni Yadi"],
        "institutions": [
            "Yobe State University, Damaturu",
            "Federal University, Gashua",
        ],
    },
    "Zamfara": {
        "lgas": [
            "Anka",
            "Bakura",
            "Birnin Magaji/Kiyaw",
            "Bukkuyum",
            "Bungudu",
            "Gummi",
            "Gusau",
            "Kaura Namoda",
            "Maradun",
            "Maru",
            "Shinkafi",
            "Talata Marafa",
            "Tsafe",
            "Zurmi",
        ],
        "cities": ["Gusau", "Kaura Namoda", "Anka", "Talata Marafa"],
        "institutions": [
            "Federal University, Gusau (FUGUS)",
            "Zamfara State University, Talata-Mafara",
        ],
    },
}
