"""create initial tables

Revision ID: 48052aaccd11
Revises: 
Create Date: 2026-01-11 17:20:31.705879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '48052aaccd11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_blacklisted_token', 'blacklisted_tokens', ['token'], unique=False)
    op.create_geospatial_table('states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_states_location', 'states', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index(op.f('ix_states_location'), 'states', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('TENANT', 'LANDLORD', 'LAWYER', 'CARETAKER', 'AGENT', 'SELLER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_endpoint'), 'idempotency_keys', ['endpoint'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_geospatial_table('local_government_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_local_government_areas_location', 'local_government_areas', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index(op.f('ix_local_government_areas_location'), 'local_government_areas', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_local_government_areas_name'), 'local_government_areas', ['name'], unique=True)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'credential_id', name='unique_user_credential'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='unique_user_device'),
    sa.UniqueConstraint('user_id', 'public_key', name='unique_user_publickey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_pic_path', sa.String(length=512), nullable=False),
    sa.Column('profile_pic_hash', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('nin_hash', sa.String(length=256), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderchoices', native_enum=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('verification_error', sa.Text(), nullable=True),
    sa.Column('state_of_birth', sa.String(length=60), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('verification_provider', sa.Enum('YOU_VERIFY', 'QORE_ID', 'PREMBLY', 'NONE_YET', name='verificationproviders', native_enum=False), nullable=False),
    sa.Column('profile_pic_uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin_hash'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_date_of_birth'), 'user_profiles', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_is_verified'), 'user_profiles', ['is_verified'], unique=False)
    op.create_index(op.f('ix_user_profiles_profile_pic_hash'), 'user_profiles', ['profile_pic_hash'], unique=False)
    op.create_index(op.f('ix_user_profiles_profile_pic_path'), 'user_profiles', ['profile_pic_path'], unique=False)
    op.create_index(op.f('ix_user_profiles_verification_status'), 'user_profiles', ['verification_status'], unique=False)
    op.create_index(op.f('ix_user_profiles_verified_at'), 'user_profiles', ['verified_at'], unique=False)
    op.create_geospatial_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('managed_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('lga_id', sa.UUID(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('toilets', sa.Integer(), nullable=True),
    sa.Column('default_rent_amount', sa.Integer(), nullable=True),
    sa.Column('default_rent_cycle', sa.String(length=20), nullable=True),
    sa.Column('house_type', sa.Enum('SELF_CON', 'ONE_BEDROOM_FLAT', 'TWO_BEDROOM_FLAT', 'THREE_BEDROOM_FLAT', 'DUPLEX', 'BUNGALOW', name='housetype', native_enum=False), nullable=False),
    sa.Column('property_type', sa.Enum('LAND', 'BUNGALOW', 'DUPLEX', 'TERRACE', 'FLAT', 'SELF_CON', 'COMMERCIAL_BUILDING', 'OFFICE_SPACE', name='propertytypes', native_enum=False), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('square_meters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['local_government_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['managed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_properties_location', 'properties', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_properties_lga_id'), 'properties', ['lga_id'], unique=False)
    op.create_index(op.f('ix_properties_managed_by_id'), 'properties', ['managed_by_id'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_state_id'), 'properties', ['state_id'], unique=False)
    op.create_table('rental_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('has_water', sa.Boolean(), nullable=False),
    sa.Column('has_electricity', sa.Boolean(), nullable=False),
    sa.Column('listed_by_id', sa.UUID(), nullable=False),
    sa.Column('rental_listed_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('lga_id', sa.UUID(), nullable=True),
    sa.Column('rent_duration', sa.Enum('YEARLY', 'QUARTERLY', 'MONTHLY', name='rentduration', native_enum=False), nullable=False),
    sa.Column('furnished_level', sa.Enum('FURNISHED', 'SEMI_FURNISHED', 'UNFURNISHED', name='furnishing', native_enum=False), nullable=False),
    sa.Column('house_type', sa.Enum('SELF_CON', 'ONE_BEDROOM_FLAT', 'TWO_BEDROOM_FLAT', 'THREE_BEDROOM_FLAT', 'DUPLEX', 'BUNGALOW', name='housetype', native_enum=False), nullable=False),
    sa.Column('property_type', sa.Enum('LAND', 'BUNGALOW', 'DUPLEX', 'TERRACE', 'FLAT', 'SELF_CON', 'COMMERCIAL_BUILDING', 'OFFICE_SPACE', name='propertytypes', native_enum=False), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('toilets', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['local_government_areas.id'], ),
    sa.ForeignKeyConstraint(['listed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_listed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_rental_listings_furnished_level'), 'rental_listings', ['furnished_level'], unique=False)
    op.create_index(op.f('ix_rental_listings_house_type'), 'rental_listings', ['house_type'], unique=False)
    op.create_index(op.f('ix_rental_listings_is_available'), 'rental_listings', ['is_available'], unique=False)
    op.create_index(op.f('ix_rental_listings_is_verified'), 'rental_listings', ['is_verified'], unique=False)
    op.create_index(op.f('ix_rental_listings_listed_by_id'), 'rental_listings', ['listed_by_id'], unique=False)
    op.create_index(op.f('ix_rental_listings_property_type'), 'rental_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_rental_listings_rent_duration'), 'rental_listings', ['rent_duration'], unique=False)
    op.create_index(op.f('ix_rental_listings_rental_listed_by'), 'rental_listings', ['rental_listed_by'], unique=False)
    op.create_table('sale_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listed_by_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('lga_id', sa.UUID(), nullable=True),
    sa.Column('sale_listed_by', sa.UUID(), nullable=True),
    sa.Column('plot_size', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('toilets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['local_government_areas.id'], ),
    sa.ForeignKeyConstraint(['listed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_listed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_listings_listed_by_id'), 'sale_listings', ['listed_by_id'], unique=False)
    op.create_index(op.f('ix_sale_listings_sale_listed_by'), 'sale_listings', ['sale_listed_by'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('property_image_creator', sa.UUID(), nullable=True),
    sa.Column('property_by_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_image_creator'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_property_images_image_hash'), 'property_images', ['image_hash'], unique=False)
    op.create_index(op.f('ix_property_images_property_by_id'), 'property_images', ['property_by_id'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_images_property_image_creator'), 'property_images', ['property_image_creator'], unique=False)
    op.create_table('rental_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('last_viewing_set_by', sa.UUID(), nullable=True),
    sa.Column('viewing_date', sa.DateTime(), nullable=True),
    sa.Column('viewing_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('renter_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_viewing_set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['rental_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'renter_id', name='uq_listing_renter')
    )
    op.create_index(op.f('ix_rental_conversations_listing_id'), 'rental_conversations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rental_conversations_owner_id'), 'rental_conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_rental_conversations_renter_id'), 'rental_conversations', ['renter_id'], unique=False)
    op.create_table('rental_listing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('rental_image_creator', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['rental_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_image_creator'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_rental_listing_images_created_by_id'), 'rental_listing_images', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_rental_listing_images_image_hash'), 'rental_listing_images', ['image_hash'], unique=False)
    op.create_index(op.f('ix_rental_listing_images_listing_id'), 'rental_listing_images', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rental_listing_images_rental_image_creator'), 'rental_listing_images', ['rental_image_creator'], unique=False)
    op.create_table('sale_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('last_viewing_set_by', sa.UUID(), nullable=True),
    sa.Column('viewing_date', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('viewing_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_viewing_set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['sale_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_id', name='uq_listing_buyer')
    )
    op.create_index(op.f('ix_sale_conversations_buyer_id'), 'sale_conversations', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sale_conversations_listing_id'), 'sale_conversations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sale_conversations_seller_id'), 'sale_conversations', ['seller_id'], unique=False)
    op.create_table('sale_listing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('sale_image_creator', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['sale_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_image_creator'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_sale_listing_images_created_by_id'), 'sale_listing_images', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_sale_listing_images_image_hash'), 'sale_listing_images', ['image_hash'], unique=False)
    op.create_index(op.f('ix_sale_listing_images_image_path'), 'sale_listing_images', ['image_path'], unique=False)
    op.create_index(op.f('ix_sale_listing_images_listing_id'), 'sale_listing_images', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sale_listing_images_sale_image_creator'), 'sale_listing_images', ['sale_image_creator'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('matched_user_id', sa.UUID(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_cycle', sa.Enum('MONTHLY', 'YEARLY', name='rentcycle', native_enum=False), nullable=False),
    sa.Column('rent_start_date', sa.Date(), nullable=False),
    sa.Column('rent_expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_first_name'), 'tenants', ['first_name'], unique=False)
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_last_name'), 'tenants', ['last_name'], unique=False)
    op.create_index(op.f('ix_tenants_matched_user_id'), 'tenants', ['matched_user_id'], unique=False)
    op.create_index(op.f('ix_tenants_middle_name'), 'tenants', ['middle_name'], unique=False)
    op.create_index(op.f('ix_tenants_property_id'), 'tenants', ['property_id'], unique=False)
    op.create_index(op.f('ix_tenants_rent_cycle'), 'tenants', ['rent_cycle'], unique=False)
    op.create_table('rent_ledgers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_ledgers_tenant_id'), 'rent_ledgers', ['tenant_id'], unique=False)
    op.create_table('rent_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('receipt_path', sa.String(length=512), nullable=True),
    sa.Column('landlord_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('month_paid_for', sa.Integer(), nullable=True),
    sa.Column('year_paid_for', sa.Integer(), nullable=True),
    sa.Column('rent_duration_months', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=69), nullable=True),
    sa.Column('barcode_reference', sa.String(length=69), nullable=True),
    sa.Column('pdf_status', sa.Enum('PENDING', 'GENERATING', 'FAILED', 'READY', name='pdf_status', native_enum=False), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_reference'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_rent_receipts_pdf_status'), 'rent_receipts', ['pdf_status'], unique=False)
    op.create_index(op.f('ix_rent_receipts_public_id'), 'rent_receipts', ['public_id'], unique=True)
    op.create_table('rental_encrypted_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('sender_public_key', sa.Text(), nullable=False),
    sa.Column('sender_deleted', sa.Boolean(), nullable=False),
    sa.Column('receiver_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['rental_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_encrypted_messages_conversation_id'), 'rental_encrypted_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_rental_encrypted_messages_receiver_id'), 'rental_encrypted_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_rental_encrypted_messages_sender_id'), 'rental_encrypted_messages', ['sender_id'], unique=False)
    op.create_table('rental_viewing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convo_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['convo_id'], ['rental_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_viewing_history_convo_id'), 'rental_viewing_history', ['convo_id'], unique=False)
    op.create_table('sales_encrypted_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('sender_public_key', sa.Text(), nullable=False),
    sa.Column('sender_deleted', sa.Boolean(), nullable=False),
    sa.Column('receiver_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['sale_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_encrypted_messages_conversation_id'), 'sales_encrypted_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sales_encrypted_messages_receiver_id'), 'sales_encrypted_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_sales_encrypted_messages_sender_id'), 'sales_encrypted_messages', ['sender_id'], unique=False)
    op.create_table('sales_viewing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convo_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'CANCELLED', name='viewingstatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['convo_id'], ['sale_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_viewing_history_convo_id'), 'sales_viewing_history', ['convo_id'], unique=False)
    op.create_table('rent_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('rent_receipt_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'REJECTED', name='rent_payment_status', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rent_receipt_id'], ['rent_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_rent_proofs_property_id'), 'rent_proofs', ['property_id'], unique=False)
    op.create_index(op.f('ix_rent_proofs_rent_receipt_id'), 'rent_proofs', ['rent_receipt_id'], unique=False)
    op.create_index(op.f('ix_rent_proofs_status'), 'rent_proofs', ['status'], unique=False)
    op.create_index(op.f('ix_rent_proofs_tenant_id'), 'rent_proofs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rent_proofs_tenant_id'), table_name='rent_proofs')
    op.drop_index(op.f('ix_rent_proofs_status'), table_name='rent_proofs')
    op.drop_index(op.f('ix_rent_proofs_rent_receipt_id'), table_name='rent_proofs')
    op.drop_index(op.f('ix_rent_proofs_property_id'), table_name='rent_proofs')
    op.drop_table('rent_proofs')
    op.drop_index(op.f('ix_sales_viewing_history_convo_id'), table_name='sales_viewing_history')
    op.drop_table('sales_viewing_history')
    op.drop_index(op.f('ix_sales_encrypted_messages_sender_id'), table_name='sales_encrypted_messages')
    op.drop_index(op.f('ix_sales_encrypted_messages_receiver_id'), table_name='sales_encrypted_messages')
    op.drop_index(op.f('ix_sales_encrypted_messages_conversation_id'), table_name='sales_encrypted_messages')
    op.drop_table('sales_encrypted_messages')
    op.drop_index(op.f('ix_rental_viewing_history_convo_id'), table_name='rental_viewing_history')
    op.drop_table('rental_viewing_history')
    op.drop_index(op.f('ix_rental_encrypted_messages_sender_id'), table_name='rental_encrypted_messages')
    op.drop_index(op.f('ix_rental_encrypted_messages_receiver_id'), table_name='rental_encrypted_messages')
    op.drop_index(op.f('ix_rental_encrypted_messages_conversation_id'), table_name='rental_encrypted_messages')
    op.drop_table('rental_encrypted_messages')
    op.drop_index(op.f('ix_rent_receipts_public_id'), table_name='rent_receipts')
    op.drop_index(op.f('ix_rent_receipts_pdf_status'), table_name='rent_receipts')
    op.drop_table('rent_receipts')
    op.drop_index(op.f('ix_rent_ledgers_tenant_id'), table_name='rent_ledgers')
    op.drop_table('rent_ledgers')
    op.drop_index(op.f('ix_tenants_rent_cycle'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_property_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_middle_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_matched_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_last_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_first_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sale_listing_images_sale_image_creator'), table_name='sale_listing_images')
    op.drop_index(op.f('ix_sale_listing_images_listing_id'), table_name='sale_listing_images')
    op.drop_index(op.f('ix_sale_listing_images_image_path'), table_name='sale_listing_images')
    op.drop_index(op.f('ix_sale_listing_images_image_hash'), table_name='sale_listing_images')
    op.drop_index(op.f('ix_sale_listing_images_created_by_id'), table_name='sale_listing_images')
    op.drop_table('sale_listing_images')
    op.drop_index(op.f('ix_sale_conversations_seller_id'), table_name='sale_conversations')
    op.drop_index(op.f('ix_sale_conversations_listing_id'), table_name='sale_conversations')
    op.drop_index(op.f('ix_sale_conversations_buyer_id'), table_name='sale_conversations')
    op.drop_table('sale_conversations')
    op.drop_index(op.f('ix_rental_listing_images_rental_image_creator'), table_name='rental_listing_images')
    op.drop_index(op.f('ix_rental_listing_images_listing_id'), table_name='rental_listing_images')
    op.drop_index(op.f('ix_rental_listing_images_image_hash'), table_name='rental_listing_images')
    op.drop_index(op.f('ix_rental_listing_images_created_by_id'), table_name='rental_listing_images')
    op.drop_table('rental_listing_images')
    op.drop_index(op.f('ix_rental_conversations_renter_id'), table_name='rental_conversations')
    op.drop_index(op.f('ix_rental_conversations_owner_id'), table_name='rental_conversations')
    op.drop_index(op.f('ix_rental_conversations_listing_id'), table_name='rental_conversations')
    op.drop_table('rental_conversations')
    op.drop_index(op.f('ix_property_images_property_image_creator'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_property_by_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_image_hash'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_sale_listings_sale_listed_by'), table_name='sale_listings')
    op.drop_index(op.f('ix_sale_listings_listed_by_id'), table_name='sale_listings')
    op.drop_table('sale_listings')
    op.drop_index(op.f('ix_rental_listings_rental_listed_by'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_rent_duration'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_property_type'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_listed_by_id'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_is_verified'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_is_available'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_house_type'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_furnished_level'), table_name='rental_listings')
    op.drop_table('rental_listings')
    op.drop_index(op.f('ix_properties_state_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_managed_by_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_lga_id'), table_name='properties')
    op.drop_geospatial_index('idx_properties_location', table_name='properties', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('properties')
    op.drop_index(op.f('ix_user_profiles_verified_at'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_verification_status'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_pic_path'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_pic_hash'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_verified'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_date_of_birth'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_local_government_areas_name'), table_name='local_government_areas')
    op.drop_geospatial_index(op.f('ix_local_government_areas_location'), table_name='local_government_areas', column_name='location')
    op.drop_geospatial_index('idx_local_government_areas_location', table_name='local_government_areas', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('local_government_areas')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_endpoint'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('users')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_geospatial_index(op.f('ix_states_location'), table_name='states', column_name='location')
    op.drop_geospatial_index('idx_states_location', table_name='states', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('states')
    op.drop_index('idx_blacklisted_token', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
